# Personalize your website info here
title:            Emile Latour
tagline:          'Fighting cancer with math'
description:      'Website and Blog for Emile Latour, a biostatistician working in cancer research'
url:              http://anewguy.github.io
author:
  name:           'Emile Latour'
  url:            https://twitter.com/anewguy

## You don't need to modify below this line
paginate:         5

# Custom vars
version:          2.1.0
github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-paginate,jekyll-gist, redcarpet]
paginate: 5
paginate_path: "page:num"

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
baseurl:          /
